// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BackendTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void backend() {
    driver.get("https://phptravels.net/api/admin");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("admin@phptravels.com");
    driver.findElement(By.cssSelector(".btn-block")).click();
    driver.findElement(By.cssSelector(".btn-block")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector(".iCheck-helper")).click();
    driver.findElement(By.name("password")).sendKeys("demoadmin");
    driver.findElement(By.cssSelector(".btn-block")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-block"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".alert")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".alert"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".btn-primary > .h5")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .btn-primary")).click();
    vars.put("win415", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win415").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win415").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".col-md-6:nth-child(1) .col-md-4:nth-child(3) strong")).click();
    driver.findElement(By.id("payment_status")).click();
    {
      WebElement dropdown = driver.findElement(By.id("payment_status"));
      dropdown.findElement(By.xpath("//option[. = 'Paid']")).click();
    }
    driver.findElement(By.id("booking_status")).click();
    driver.findElement(By.id("booking_status")).click();
    {
      WebElement dropdown = driver.findElement(By.id("booking_status"));
      dropdown.findElement(By.xpath("//option[. = 'Confirmed']")).click();
    }
    driver.findElement(By.cssSelector(".col-md-6:nth-child(1) .col-md-4:nth-child(4) .panel-body")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .btn-primary")).click();
    vars.put("win1237", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1237").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win1237").toString());
    driver.findElement(By.cssSelector(".mb-4")).click();
    driver.findElement(By.name("payment_gateway")).click();
    {
      WebElement dropdown = driver.findElement(By.name("payment_gateway"));
      dropdown.findElement(By.xpath("//option[. = 'bank transfer']")).click();
    }
    driver.findElement(By.id("form")).click();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".col-md-6:nth-child(2) .col-md-4:nth-child(3) strong")).click();
    driver.findElement(By.cssSelector(".btn > div")).click();
    driver.findElement(By.id("servicetype")).click();
    {
      WebElement dropdown = driver.findElement(By.id("servicetype"));
      dropdown.findElement(By.xpath("//option[. = 'Hotels']")).click();
    }
    driver.findElement(By.cssSelector(".pace-done")).click();
    driver.findElement(By.cssSelector(".col-md-3 > #Hotels")).click();
    driver.findElement(By.cssSelector(".datepicker:nth-child(27) tr:nth-child(2) > .day:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".datepicker:nth-child(27) tr:nth-child(6) > .day:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".panel:nth-child(19) > .panel-body")).click();
    driver.findElement(By.cssSelector(".pace-done")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_poprooms .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".pace-done")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#s2id_poprooms .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".pace-done")).click();
    driver.findElement(By.name("paymethod")).click();
    {
      WebElement dropdown = driver.findElement(By.name("paymethod"));
      dropdown.findElement(By.xpath("//option[. = 'Bank Transfer']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("pre")).click();
    driver.findElement(By.cssSelector("pre")).click();
    driver.findElement(By.cssSelector("pre")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("pre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("pre")).click();
    driver.findElement(By.cssSelector("pre")).click();
    driver.findElement(By.cssSelector(".pace-done")).click();
    driver.findElement(By.cssSelector(".panel:nth-child(5) > .panel-body")).click();
    driver.findElement(By.linkText("Rooms")).click();
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .btn-default")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col-md-12:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".room-form")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".room-form"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("cke_1_bottom")).click();
    driver.findElement(By.name("basicprice")).sendKeys("49");
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector("p")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".cke_editable"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Tidak ada&nbsp;</p>'}", element);
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.id("update")).click();
    driver.findElement(By.linkText("Airports")).click();
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .xcrud-action:nth-child(1) > .fa")).click();
    driver.findElement(By.cssSelector(".btn-warning")).click();
    driver.findElement(By.cssSelector("li:nth-child(3) .fa-list")).click();
    driver.findElement(By.linkText("Bookings")).click();
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .btn-danger > .fa")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure to delete?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".dropdown:nth-child(6) > .dropdown-toggle")).click();
    driver.findElement(By.linkText("Searches")).click();
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) > td:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) > td:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) > td:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .checkboxcls")).click();
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .btn-info")).click();
    driver.findElement(By.cssSelector(".btn-warning")).click();
    driver.findElement(By.cssSelector("#deleteAll > strong")).click();
    assertThat(driver.switchTo().alert().getText(), is("Please at least select one item."));
    driver.findElement(By.id("select_all")).click();
    driver.findElement(By.id("deleteAll")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to delete?"));
    driver.switchTo().alert().accept();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".xcrud-in-new-window:nth-child(2)")).click();
    vars.put("win514", waitForWindow(2000));
    driver.switchTo().window(vars.get("win514").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("Payouts")).click();
    driver.findElement(By.cssSelector(".open > .dropdown-menu a")).click();
    driver.findElement(By.cssSelector("td:nth-child(8) > #\\33")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to mark this transaction paid?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.linkText("Bookings")).click();
    driver.findElement(By.cssSelector(".xcrud-row:nth-child(1) .btn-danger > .fa")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure to delete?"));
    driver.switchTo().alert().accept();
  }
}
