// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HotelsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hotelsTest() {
    driver.get("https://www.phptravels.net/hotels");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.cssSelector(".owl-dots")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".owl-item:nth-child(6) .btn-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".owl-item:nth-child(6) .btn-text")).click();
    driver.findElement(By.cssSelector(".g-0:nth-child(1) > .img-fluid")).click();
    driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg")).click();
    driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg")).click();
    driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg")).click();
    driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg")).click();
    driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".fancybox-button--arrow_right svg")).click();
    driver.findElement(By.cssSelector(".fancybox-button--close > svg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".card:nth-child(1) .ladda-label:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys("Jakarta");
    {
      WebElement element = driver.findElement(By.cssSelector(".ladda-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".ladda-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".focus-visible")).click();
    driver.findElement(By.cssSelector(".list")).click();
    driver.findElement(By.cssSelector("li:nth-child(4) .custom-control-label")).click();
    driver.findElement(By.cssSelector("li:nth-child(3) .custom-control-label")).click();
    driver.findElement(By.cssSelector(".js-irs-0 > .irs-bar")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(4) .custom-control-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(4) .custom-control-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(4) .custom-control-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".sidebar-widget > form")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#icorner\\ residence .col-4 .la"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#icorner\\ residence .col-4 .la")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#icorner\\ residence .ladda-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#icorner\\ residence .ladda-label"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,491)");
    {
      WebElement element = driver.findElement(By.linkText("Hotels"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Hotels")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".header-area:nth-child(29) > .header-menu-wrapper:nth-child(2) li:nth-child(7) > .waves-effect:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".header-area:nth-child(29) > .header-menu-wrapper:nth-child(2) li:nth-child(7) > .waves-effect:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Home"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Home"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Hotels"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Hotels"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-hotels_city-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-search__field"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys("London");
    {
      WebElement element = driver.findElement(By.cssSelector(".ladda-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".ladda-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,244)");
    driver.findElement(By.cssSelector("#publove\\ \\@\\ the\\ crown .ladda-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#publove\\ \\@\\ the\\ crown .ladda-label"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#publove\\ \\@\\ the\\ crown .col-4 .la"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Back to Home")).click();
  }
}
