// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginTest() {
    driver.get("https://www.phptravels.net/login");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("shins.parila");
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-lg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".btn-lg")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("form > .input-box:nth-child(1) > .form-group")).click();
    driver.findElement(By.name("email")).sendKeys("sarahmanuella21@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).click();
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-lg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".btn-lg")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-lg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("password")).sendKeys("ronatiur09");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(2) > label")).click();
    driver.findElement(By.cssSelector(".focus-visible")).click();
    driver.findElement(By.cssSelector(".focus-visible")).sendKeys("sarahmanuella21@gmail.com");
    driver.findElement(By.cssSelector(".ladda")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector(".mt-5")).click();
    driver.findElement(By.linkText("Signup")).click();
    driver.findElement(By.name("first_name")).click();
    driver.findElement(By.name("first_name")).sendKeys("Ronatiur Febriani");
    driver.findElement(By.name("last_name")).click();
    driver.findElement(By.name("last_name")).sendKeys("Lumban Gaol");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("081310752184");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("ronatiurfebriani09@gmail.com");
    driver.findElement(By.cssSelector(".input-box:nth-child(5) > .form-group")).click();
    driver.findElement(By.name("email")).sendKeys("sarahmanuella21@gmail.com");
    driver.findElement(By.name("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-lg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("password")).sendKeys("rona");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("sarahmanuella21@gmail.com");
    driver.findElement(By.name("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-lg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("password")).sendKeys("r");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("ronatiurfebriani09@gmail.com");
    {
      WebElement element = driver.findElement(By.cssSelector(".col > .modal-body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col > .modal-body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col > .modal-body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".col > .modal-body")).click();
    driver.findElement(By.name("email")).sendKeys("sarahmanuella21@gmail.com");
    driver.findElement(By.name("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-lg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("password")).sendKeys("rona");
    driver.findElement(By.cssSelector(".btn-lg")).click();
  }
}
