// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SidebartestDashboardMybookingAddfundsMyProfileLogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sidebartestDashboardMybookingAddfundsMyProfileLogout() {
    driver.get("https://www.phptravels.net/account/dashboard");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.cssSelector(".col-lg-3:nth-child(2) .info__title")).click();
    driver.findElement(By.cssSelector(".col-lg-3:nth-child(1) .info__title")).click();
    driver.findElement(By.linkText("My Bookings")).click();
    {
      WebElement element = driver.findElement(By.linkText("Add Funds"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Add Funds")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".gateway_bank-transfer .d-flex")).click();
    driver.findElement(By.id("gateway_bank-transfer")).click();
    driver.findElement(By.cssSelector(".btn-block")).click();
    driver.findElement(By.cssSelector(".btn-front")).click();
    driver.findElement(By.linkText("Yes")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Profile"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Profile")).click();
    driver.findElement(By.cssSelector(".fixed-nav")).click();
    driver.findElement(By.name("state")).click();
    driver.findElement(By.name("state")).sendKeys("SUMATERA UTARA");
    driver.findElement(By.name("city")).sendKeys("KABUPATEN TOBA SAMOSIR");
    driver.findElement(By.name("fax")).sendKeys("KABUPATEN TOBA SAMOSIR");
    driver.findElement(By.name("zip")).sendKeys("22384");
    driver.findElement(By.name("address1")).sendKeys("Siantar Sigordang");
    driver.findElement(By.name("address2")).click();
    driver.findElement(By.name("address2")).sendKeys("London");
    driver.findElement(By.cssSelector(".theme-btn:nth-child(1)")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.linkText("Home")).click();
  }
}
