// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignUpTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signUpTest() {
    driver.get("https://www.phptravels.net/signup");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.name("first_name")).click();
    driver.findElement(By.name("first_name")).sendKeys("Ronatiur Febriani");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("(+62) 81310752184");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("shins.parila");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("putra09");
    driver.findElement(By.cssSelector(".btn-default > .ladda-label")).click();
    driver.findElement(By.name("last_name")).click();
    driver.findElement(By.name("last_name")).sendKeys("Lumban Gaol");
    driver.findElement(By.cssSelector(".btn-default > .ladda-label")).click();
  }
}
